import type { EditorCopy } from "./editorTextTypes";

export const koEditorCopy: EditorCopy = {
  brandTitle: "Blind Madeleine 에디터",
  brandSubtitle: "로컬 데이터 서버",
  toolbar: {
    refresh: "새로고침",
    create: "새 항목",
    delete: "삭제",
    save: "저장",
    play: "실행"
  },
  settings: {
    label: "환경 설정",
    language: "언어",
    korean: "한국어",
    english: "English",
    theme: "테마",
    themeMode: "화면 모드",
    dark: "다크",
    light: "라이트",
    accent: "색상",
    green: "그린",
    blue: "블루",
    rose: "로즈",
    amber: "앰버",
    custom: "사용자",
    customColor: "사용자 색상"
  },
  mobile: {
    library: "목록",
    workspace: "편집",
    inspector: "검증"
  },
  resources: {
    dialogues: "대사",
    characters: "캐릭터",
    chapters: "챕터",
    items: "아이템",
    story_assets: "스토리 에셋"
  },
  panels: {
    resourceNav: "데이터 타입",
    collection: "데이터 목록",
    library: "라이브러리",
    workspace: "편집 영역",
    inspector: "검증 패널",
    project: "프로젝트",
    validation: "검증"
  },
  tabs: {
    form: "폼",
    nodes: "노드",
    graph: "그래프",
    json: "JSON",
    preview: "미리보기"
  },
  presentationModes: {
    normal: "일반",
    talk: "대화",
    investigation: "조사",
    statement: "진술"
  },
  status: {
    jsonError: "JSON 오류",
    dirty: "수정됨",
    clean: "저장됨"
  },
  common: {
    search: "검색",
    emptyList: "표시할 항목이 없습니다.",
    format: "정렬",
    unspecified: "미지정",
    currentMissing: "현재 값",
    noneAvailable: "선택 가능한 항목이 없습니다.",
    missing: "없음",
    uploading: "업로드 중...",
    delete: "삭제",
    selectItem: "항목을 선택하세요.",
    goToPosition: "위치로 이동"
  },
  form: {
    empty: "편집할 항목을 선택하세요.",
    id: "ID / 파일명",
    label: "라벨",
    description: "설명",
    chapters: "챕터",
    startNode: "시작 노드",
    presentationMode: "표시 모드",
    nextDialogue: "다음 대사",
    metadata: "메타데이터",
    displayName: "표시 이름",
    nameColor: "이름 색상",
    protagonist: "주인공",
    voiceProfile: "보이스 프로필 메타데이터",
    title: "제목",
    order: "순서",
    startDialogue: "시작 대사",
    dialogues: "대사",
    name: "이름",
    image: "이미지",
    uploadItemImage: "아이템 이미지 업로드",
    kind: "종류",
    path: "경로",
    uploadAssetFile: "에셋 파일 업로드",
    volume: "볼륨",
    fixedBackground: "고정 배경",
    mode: "모드",
    modeDialogue: "대사",
    modeStage: "무대",
    modeCutscene: "컷씬",
    speaker: "화자",
    speakerAutoClean: "화자 자동정리",
    speakerAutoCleanConfirmManualRemove: "사용자가 직접 추가한 무대 캐릭터도 제거할까요?",
    nextNode: "다음 노드",
    speakerMystery: "화자 숨김",
    textSoundMuted: "대사음 음소거",
    text: "본문",
    fadeIn: "페이드 인",
    hold: "유지",
    fadeOut: "페이드 아웃",
    statementNotebook: "진술 노트",
    customStatementScope: "진술 노트 범위 직접 지정",
    defaultStatementScope: "기본 진술 노트 범위를 사용합니다.",
    notebookCharacters: "노트 캐릭터",
    notebookItems: "노트 아이템",
    portraits: "초상",
    addPortrait: "초상",
    noPortraits: "초상 없음",
    key: "키",
    uploadPortrait: "초상 업로드",
    center: "중심",
    centerX: "중심 X",
    centerY: "중심 Y",
    profileZoom: "프로필 확대",
    profileOffsetX: "프로필 오프셋 X",
    profileOffsetY: "프로필 오프셋 Y",
    stageCast: "무대 캐스트",
    focusTargets: "주목 목록",
    addCharacter: "캐릭터 추가",
    noStageCast: "무대 캐스트 없음",
    portrait: "초상",
    position: "위치",
    positionFarLeft: "먼 왼쪽",
    positionLeft: "왼쪽",
    positionCenter: "가운데",
    positionRight: "오른쪽",
    positionFarRight: "먼 오른쪽",
    positionCustom: "직접 지정",
    offsetX: "오프셋 X",
    offsetY: "오프셋 Y",
    positionOrder: "위치 순서",
    animationOrder: "애니메이션 순서",
    zoom: "확대",
    opacity: "불투명도",
    animationSpeed: "애니메이션 속도",
    flipX: "좌우 반전",
    mystery: "수수께끼",
    exit: "퇴장",
    stagePreview: "무대 미리보기",
    visible: "표시 중",
    previewEmpty: "미리보기 없음",
    offset: "오프셋",
    popups: "팝업",
    addPopup: "팝업",
    noPopups: "팝업 이미지 없음",
    popupKind: "종류",
    popupCharacter: "인물",
    popupItem: "아이템",
    popupImagePath: "이미지 경로",
    popupPortraitDefault: "프로필 기본",
    popupWidth: "폭",
    popupHeight: "높이",
    popupScale: "스케일",
    popupTransition: "전환",
    popupPositionTopLeft: "좌상단",
    popupPositionTopRight: "우상단",
    popupSourceCharacterProfile: "인물 프로필",
    popupSourceItem: "아이템",
    popupSourceImage: "직접 이미지",
    popupTransitionFade: "페이드",
    popupTransitionPop: "팝",
    popupTransitionSlide: "슬라이드",
    popupTransitionNone: "없음",
    popupImageMode: "이미지 모드",
    popupImageZoom: "이미지 확대",
    popupImageModeFit: "맞춤",
    popupImageModeCover: "채우기",
    popupImageModeCrop: "자르기"
  },
  preview: {
    select: "미리볼 항목을 선택하세요.",
    title: "제목",
    summary: "요약",
    eventTags: "이벤트 태그",
    parallaxLayers: "패럴랙스 레이어",
    web: "웹",
    pc: "PC",
    fold7: "Fold7",
    fold7Open: "Fold7 펼침",
    actualPreview: "실제 화면 미리보기",
    actualPreviewUnavailable: "대사 리소스에서만 실제 화면 미리보기를 사용할 수 있습니다.",
    actualPreviewReady: "실제 화면 프리뷰 준비 완료",
    actualPreviewPreparing: "실제 화면 프리뷰 준비 중",
    actualPreviewBuilding: "Godot 웹 프리뷰 빌드 중",
    actualPreviewBuild: "웹 빌드",
    godotRun: "Godot 실행",
    currentDialogue: "현재 대화",
    previousDialogue: "이전 대화",
    refresh: "새로고침",
    openInNewTab: "새 탭",
    bridgeRequired: "Godot preview bridge가 실행 중이어야 합니다."
  }
};
