import type { EditorTab, MobilePanel } from "./editorTypes";
import type { ResourceType } from "./types";

export type EditorCopy = {
  brandTitle: string;
  brandSubtitle: string;
  toolbar: Record<"refresh" | "create" | "delete" | "save" | "play", string>;
  settings: Record<
    | "label"
    | "language"
    | "korean"
    | "english"
    | "theme"
    | "themeMode"
    | "dark"
    | "light"
    | "accent"
    | "green"
    | "blue"
    | "rose"
    | "amber"
    | "custom"
    | "customColor",
    string
  >;
  mobile: Record<MobilePanel, string>;
  resources: Record<ResourceType, string>;
  panels: Record<"resourceNav" | "collection" | "library" | "workspace" | "inspector" | "project" | "validation", string>;
  tabs: Record<EditorTab, string>;
  presentationModes: Record<"normal" | "talk" | "investigation" | "statement", string>;
  status: Record<"jsonError" | "dirty" | "clean", string>;
  common: Record<"search" | "emptyList" | "format" | "unspecified" | "currentMissing" | "noneAvailable" | "missing" | "uploading" | "delete" | "selectItem" | "goToPosition", string>;
  form: Record<
    | "empty"
    | "id"
    | "label"
    | "description"
    | "chapters"
    | "startNode"
    | "presentationMode"
    | "nextDialogue"
    | "metadata"
    | "displayName"
    | "nameColor"
    | "protagonist"
    | "voiceProfile"
    | "title"
    | "order"
    | "startDialogue"
    | "dialogues"
    | "name"
    | "image"
    | "uploadItemImage"
    | "kind"
    | "path"
    | "uploadAssetFile"
    | "volume"
    | "fixedBackground"
    | "mode"
    | "modeDialogue"
    | "modeStage"
    | "modeCutscene"
    | "speaker"
    | "speakerAutoClean"
    | "speakerAutoCleanConfirmManualRemove"
    | "nextNode"
    | "speakerMystery"
    | "textSoundMuted"
    | "text"
    | "fadeIn"
    | "hold"
    | "fadeOut"
    | "statementNotebook"
    | "customStatementScope"
    | "defaultStatementScope"
    | "notebookCharacters"
    | "notebookItems"
    | "portraits"
    | "addPortrait"
    | "noPortraits"
    | "key"
    | "uploadPortrait"
    | "center"
    | "centerX"
    | "centerY"
    | "profileZoom"
    | "profileOffsetX"
    | "profileOffsetY"
    | "stageCast"
    | "focusTargets"
    | "addCharacter"
    | "noStageCast"
    | "portrait"
    | "live2dAngle"
    | "position"
    | "positionFarLeft"
    | "positionLeft"
    | "positionCenter"
    | "positionRight"
    | "positionFarRight"
    | "positionCustom"
    | "offsetX"
    | "offsetY"
    | "positionOrder"
    | "animationOrder"
    | "zoom"
    | "opacity"
    | "animationSpeed"
    | "flipX"
    | "mystery"
    | "exit"
    | "stagePreview"
    | "visible"
    | "previewEmpty"
    | "offset"
    | "popups"
    | "addPopup"
    | "noPopups"
    | "popupKind"
    | "popupCharacter"
    | "popupItem"
    | "popupImagePath"
    | "popupPortraitDefault"
    | "popupWidth"
    | "popupHeight"
    | "popupScale"
    | "popupTransition"
    | "popupPositionTopLeft"
    | "popupPositionTopRight"
    | "popupSourceCharacterProfile"
    | "popupSourceItem"
    | "popupSourceImage"
    | "popupTransitionFade"
    | "popupTransitionPop"
    | "popupTransitionSlide"
    | "popupTransitionNone"
    | "popupImageMode"
    | "popupImageZoom"
    | "popupImageModeFit"
    | "popupImageModeCover"
    | "popupImageModeCrop",
    string
  >;
  preview: Record<
    | "select"
    | "title"
    | "summary"
    | "eventTags"
    | "parallaxLayers"
    | "web"
    | "pc"
    | "fold7"
    | "fold7Open"
    | "actualPreview"
    | "actualPreviewUnavailable"
    | "actualPreviewReady"
    | "actualPreviewPreparing"
    | "actualPreviewBuilding"
    | "actualPreviewBuild"
    | "godotRun"
    | "currentDialogue"
    | "previousDialogue"
    | "refresh"
    | "openInNewTab"
    | "bridgeRequired",
    string
  >;
};
