import type { EditorCopy } from "./editorTextTypes";

export const enEditorCopy: EditorCopy = {
  brandTitle: "Blind Madeleine Editor",
  brandSubtitle: "Local data server",
  toolbar: {
    refresh: "Refresh",
    create: "New",
    delete: "Delete",
    save: "Save",
    play: "Play"
  },
  settings: {
    label: "Preferences",
    language: "Language",
    korean: "한국어",
    english: "English",
    theme: "Theme",
    themeMode: "Mode",
    dark: "Dark",
    light: "Light",
    accent: "Color",
    green: "Green",
    blue: "Blue",
    rose: "Rose",
    amber: "Amber",
    custom: "Custom",
    customColor: "Custom color"
  },
  mobile: {
    library: "Library",
    workspace: "Edit",
    inspector: "Inspect"
  },
  resources: {
    dialogues: "Dialogues",
    characters: "Characters",
    chapters: "Chapters",
    items: "Items",
    story_assets: "Story assets"
  },
  panels: {
    resourceNav: "Data type",
    collection: "Data list",
    library: "Library",
    workspace: "Workspace",
    inspector: "Inspector",
    project: "Project",
    validation: "Validation"
  },
  tabs: {
    form: "Form",
    nodes: "Nodes",
    graph: "Graph",
    json: "JSON",
    preview: "Preview"
  },
  presentationModes: {
    normal: "Normal",
    talk: "Talk",
    investigation: "Investigation",
    statement: "Statement"
  },
  status: {
    jsonError: "JSON error",
    dirty: "Unsaved",
    clean: "Saved"
  },
  common: {
    search: "Search",
    emptyList: "No items to display.",
    format: "Format",
    unspecified: "Unspecified",
    currentMissing: "Current value",
    noneAvailable: "No selectable items.",
    missing: "Missing",
    uploading: "Uploading...",
    delete: "Delete",
    selectItem: "Select an item.",
    goToPosition: "Go to position"
  },
  form: {
    empty: "Select an item to edit.",
    id: "ID / filename",
    label: "Label",
    description: "Description",
    chapters: "Chapters",
    startNode: "Start node",
    presentationMode: "Presentation mode",
    nextDialogue: "Next dialogue",
    metadata: "Metadata",
    displayName: "Display name",
    nameColor: "Name color",
    protagonist: "Protagonist",
    voiceProfile: "Voice profile metadata",
    title: "Title",
    order: "Order",
    startDialogue: "Start dialogue",
    dialogues: "Dialogues",
    name: "Name",
    image: "Image",
    uploadItemImage: "Upload item image",
    kind: "Kind",
    path: "Path",
    uploadAssetFile: "Upload asset file",
    volume: "Volume",
    fixedBackground: "Fixed background",
    mode: "Mode",
    modeDialogue: "Dialogue",
    modeStage: "Stage",
    modeCutscene: "Cutscene",
    speaker: "Speaker",
    speakerAutoClean: "Clean speakers",
    speakerAutoCleanConfirmManualRemove: "Also remove manually added stage characters?",
    nextNode: "Next node",
    speakerMystery: "Speaker mystery",
    textSoundMuted: "Text sound muted",
    text: "Text",
    fadeIn: "Fade in",
    hold: "Hold",
    fadeOut: "Fade out",
    statementNotebook: "Statement notebook",
    customStatementScope: "Custom statement notebook scope",
    defaultStatementScope: "Using the default statement notebook scope.",
    notebookCharacters: "Notebook characters",
    notebookItems: "Notebook items",
    portraits: "Portraits",
    addPortrait: "Portrait",
    noPortraits: "No portraits",
    key: "Key",
    uploadPortrait: "Upload portrait",
    center: "Center",
    centerX: "Center X",
    centerY: "Center Y",
    profileZoom: "Profile zoom",
    profileOffsetX: "Profile offset X",
    profileOffsetY: "Profile offset Y",
    stageCast: "Stage cast",
    focusTargets: "Focus targets",
    addCharacter: "Add character",
    noStageCast: "No stage cast",
    portrait: "Portrait",
    position: "Position",
    positionFarLeft: "Far left",
    positionLeft: "Left",
    positionCenter: "Center",
    positionRight: "Right",
    positionFarRight: "Far right",
    positionCustom: "Custom",
    offsetX: "Offset X",
    offsetY: "Offset Y",
    positionOrder: "Position order",
    animationOrder: "Animation order",
    zoom: "Zoom",
    opacity: "Opacity",
    animationSpeed: "Animation speed",
    flipX: "Flip X",
    mystery: "Mystery",
    portraitRigAutoPose: "Portrait Rig auto pose",
    portraitRigPoseHint: "Portrait Rig pose hint",
    portraitRigPoseHintPreset: "Pose hint preset",
    portraitRigPoseHintCustom: "Custom pose hint",
    portraitRigMotionLoop: "Motion loop",
    portraitRigDialogueMotion: "Dialogue motion",
    portraitRigDialogueDefaults: "Dialogue defaults",
    portraitRigSyncExports: "Sync Portrait Rig data",
    portraitRigMotionClip: "Portrait Rig motion",
    portraitRigIdleMotionClip: "Idle motion",
    portraitRigTalkMotionClip: "Talk motion",
    portraitRigVisemeMotionClip: "Viseme motion",
    portraitRigMotionTime: "Motion time",
    portraitRigMotionProgress: "Motion progress",
    portraitRigMotionSpeed: "Motion speed",
    portraitRigMotionBlendDuration: "Motion blend",
    portraitRigMotionAutoCycle: "Auto cycle",
    exit: "Exit",
    stagePreview: "Stage Preview",
    visible: "visible",
    previewEmpty: "preview empty",
    offset: "offset",
    popups: "Popups",
    addPopup: "Popup",
    noPopups: "No popup images",
    popupKind: "Source",
    popupCharacter: "Character",
    popupItem: "Item",
    popupImagePath: "Image path",
    popupPortraitDefault: "Profile default",
    popupWidth: "Width",
    popupHeight: "Height",
    popupScale: "Scale",
    popupTransition: "Transition",
    popupPositionTopLeft: "Top left",
    popupPositionTopRight: "Top right",
    popupSourceCharacterProfile: "Character profile",
    popupSourceItem: "Item",
    popupSourceImage: "Direct image",
    popupTransitionFade: "Fade",
    popupTransitionPop: "Pop",
    popupTransitionSlide: "Slide",
    popupTransitionNone: "None",
    popupImageMode: "Image mode",
    popupImageZoom: "Image zoom",
    popupImageModeFit: "Fit",
    popupImageModeCover: "Cover",
    popupImageModeCrop: "Crop"
  },
  preview: {
    select: "Select an item to preview.",
    title: "Title",
    summary: "Summary",
    eventTags: "Event tags",
    parallaxLayers: "Parallax layers",
    web: "Web",
    pc: "PC",
    fold7: "Fold7",
    fold7Open: "Fold7 open",
    actualPreview: "Runtime preview",
    actualPreviewUnavailable: "Runtime preview is available for dialogue resources only.",
    actualPreviewReady: "Runtime preview is ready",
    actualPreviewPreparing: "Preparing runtime preview",
    actualPreviewBuilding: "Building Godot web preview",
    actualPreviewBuild: "Build web",
    godotRun: "Run Godot",
    currentDialogue: "Current dialogue",
    previousDialogue: "Previous dialogue",
    refresh: "Refresh",
    openInNewTab: "New tab",
    bridgeRequired: "Godot preview bridge must be running."
  }
};
